#ifndef PORT_PRV_H
#define PORT_PRV_H
#define PULLED_UP 1
#define FLOATING  0

#define HIGH 1
#define LOW 0

#define INPUT 0
#define OUTPUT 1

#define conc(b7,b6,b5,b4,b3,b2,b1,b0) conc_help(b7,b6,b5,b4,b3,b2,b1,b0)
#define conc_help(b7,b6,b5,b4,b3,b2,b1,b0) 0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIRECTION    conc(PORTA_PIN7_DIRECTION,PORTA_PIN6_DIRECTION,PORTA_PIN5_DIRECTION,PORTA_PIN4_DIRECTION,PORTA_PIN3_DIRECTION,PORTA_PIN2_DIRECTION,PORTA_PIN1_DIRECTION,PORTA_PIN0_DIRECTION)
#define PORTB_DIRECTION    conc(PORTB_PIN7_DIRECTION,PORTB_PIN6_DIRECTION,PORTB_PIN5_DIRECTION,PORTB_PIN4_DIRECTION,PORTB_PIN3_DIRECTION,PORTB_PIN2_DIRECTION,PORTB_PIN1_DIRECTION,PORTB_PIN0_DIRECTION)
#define PORTC_DIRECTION    conc(PORTC_PIN7_DIRECTION,PORTC_PIN6_DIRECTION,PORTC_PIN5_DIRECTION,PORTC_PIN4_DIRECTION,PORTC_PIN3_DIRECTION,PORTC_PIN2_DIRECTION,PORTC_PIN1_DIRECTION,PORTC_PIN0_DIRECTION)
#define PORTD_DIRECTION    conc(PORTD_PIN7_DIRECTION,PORTD_PIN6_DIRECTION,PORTD_PIN5_DIRECTION,PORTD_PIN4_DIRECTION,PORTD_PIN3_DIRECTION,PORTD_PIN2_DIRECTION,PORTD_PIN1_DIRECTION,PORTD_PIN0_DIRECTION)


#define PORTA_INIT_VAL    conc(PORTA_PIN7_INIT_VAL,PORTA_PIN6_INIT_VAL,PORTA_PIN5_INIT_VAL,PORTA_PIN4_INIT_VAL,PORTA_PIN3_INIT_VAL,PORTA_PIN2_INIT_VAL,PORTA_PIN1_INIT_VAL,PORTA_PIN0_INIT_VAL)
#define PORTB_INIT_VAL    conc(PORTB_PIN7_INIT_VAL,PORTB_PIN6_INIT_VAL,PORTB_PIN5_INIT_VAL,PORTB_PIN4_INIT_VAL,PORTB_PIN3_INIT_VAL,PORTB_PIN2_INIT_VAL,PORTB_PIN1_INIT_VAL,PORTB_PIN0_INIT_VAL)
#define PORTC_INIT_VAL    conc(PORTC_PIN7_INIT_VAL,PORTC_PIN6_INIT_VAL,PORTC_PIN5_INIT_VAL,PORTC_PIN4_INIT_VAL,PORTC_PIN3_INIT_VAL,PORTC_PIN2_INIT_VAL,PORTC_PIN1_INIT_VAL,PORTC_PIN0_INIT_VAL)
#define PORTD_INIT_VAL    conc(PORTD_PIN7_INIT_VAL,PORTD_PIN6_INIT_VAL,PORTD_PIN5_INIT_VAL,PORTD_PIN4_INIT_VAL,PORTD_PIN3_INIT_VAL,PORTD_PIN2_INIT_VAL,PORTD_PIN1_INIT_VAL,PORTD_PIN0_INIT_VAL)


#endif