#ifndef PORT_CFG_H
#define PORT_CFG_H
/*Pick the direction of every pin of the mcu 1)INPUT
											 2)OUTPUT*/
#define PORTA_PIN0_DIRECTION INPUT
#define PORTA_PIN1_DIRECTION INPUT
#define PORTA_PIN2_DIRECTION INPUT
#define PORTA_PIN3_DIRECTION INPUT
#define PORTA_PIN4_DIRECTION INPUT
#define PORTA_PIN5_DIRECTION INPUT
#define PORTA_PIN6_DIRECTION INPUT
#define PORTA_PIN7_DIRECTION INPUT

#define PORTB_PIN0_DIRECTION INPUT
#define PORTB_PIN1_DIRECTION INPUT
#define PORTB_PIN2_DIRECTION INPUT
#define PORTB_PIN3_DIRECTION INPUT
#define PORTB_PIN4_DIRECTION INPUT
#define PORTB_PIN5_DIRECTION INPUT
#define PORTB_PIN6_DIRECTION INPUT
#define PORTB_PIN7_DIRECTION INPUT

#define PORTC_PIN0_DIRECTION INPUT
#define PORTC_PIN1_DIRECTION INPUT
#define PORTC_PIN2_DIRECTION INPUT
#define PORTC_PIN3_DIRECTION INPUT
#define PORTC_PIN4_DIRECTION INPUT
#define PORTC_PIN5_DIRECTION INPUT
#define PORTC_PIN6_DIRECTION INPUT
#define PORTC_PIN7_DIRECTION INPUT

#define PORTD_PIN0_DIRECTION INPUT
#define PORTD_PIN1_DIRECTION INPUT
#define PORTD_PIN2_DIRECTION INPUT
#define PORTD_PIN3_DIRECTION INPUT
#define PORTD_PIN4_DIRECTION INPUT
#define PORTD_PIN5_DIRECTION INPUT
#define PORTD_PIN6_DIRECTION INPUT
#define PORTD_PIN7_DIRECTION INPUT


/*If pin is input pick its initial state of these 2 options 1)FLOATING  , But if teh pin is out pick its initial state from 1)HIGH 
															2)PULLED_UP														2)LOW*/
#define PORTA_PIN0_INIT_VAL PULLED_UP
#define PORTA_PIN1_INIT_VAL PULLED_UP
#define PORTA_PIN2_INIT_VAL PULLED_UP
#define PORTA_PIN3_INIT_VAL PULLED_UP
#define PORTA_PIN4_INIT_VAL PULLED_UP
#define PORTA_PIN5_INIT_VAL PULLED_UP
#define PORTA_PIN6_INIT_VAL PULLED_UP
#define PORTA_PIN7_INIT_VAL PULLED_UP

#define PORTB_PIN0_INIT_VAL PULLED_UP
#define PORTB_PIN1_INIT_VAL PULLED_UP
#define PORTB_PIN2_INIT_VAL PULLED_UP
#define PORTB_PIN3_INIT_VAL PULLED_UP
#define PORTB_PIN4_INIT_VAL PULLED_UP
#define PORTB_PIN5_INIT_VAL PULLED_UP
#define PORTB_PIN6_INIT_VAL PULLED_UP
#define PORTB_PIN7_INIT_VAL PULLED_UP

#define PORTC_PIN0_INIT_VAL PULLED_UP
#define PORTC_PIN1_INIT_VAL PULLED_UP
#define PORTC_PIN2_INIT_VAL PULLED_UP
#define PORTC_PIN3_INIT_VAL PULLED_UP
#define PORTC_PIN4_INIT_VAL PULLED_UP
#define PORTC_PIN5_INIT_VAL PULLED_UP
#define PORTC_PIN6_INIT_VAL PULLED_UP
#define PORTC_PIN7_INIT_VAL PULLED_UP

#define PORTD_PIN0_INIT_VAL PULLED_UP
#define PORTD_PIN1_INIT_VAL PULLED_UP
#define PORTD_PIN2_INIT_VAL PULLED_UP
#define PORTD_PIN3_INIT_VAL PULLED_UP
#define PORTD_PIN4_INIT_VAL PULLED_UP
#define PORTD_PIN5_INIT_VAL PULLED_UP
#define PORTD_PIN6_INIT_VAL PULLED_UP
#define PORTD_PIN7_INIT_VAL PULLED_UP													

#endif